version: 2
updates:

  - package-ecosystem: gomod
    directory: /
    commit-message:
      prefix: "chore(go): "
    schedule:
      interval: daily
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(actions): "
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
