// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	GetAll(ctx context.Context) ([]Beer, error)
	InsertBeer(ctx context.Context, arg InsertBeerParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
