// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAll(ctx context.Context) ([]Beer, error)
	GetAllByFamily(ctx context.Context, family pgtype.Text) ([]Beer, error)
	GetAllByFamilyLimit(ctx context.Context, arg GetAllByFamilyLimitParams) ([]Beer, error)
	InsertBeer(ctx context.Context, arg InsertBeerParams) (int32, error)
	UpdateBeerScore(ctx context.Context, id int32) (Beer, error)
}

var _ Querier = (*Queries)(nil)
