// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	GetByID(ctx context.Context, id int32) (Championship, error)
	InsertChampionship(ctx context.Context, rounds []byte) (Championship, error)
	UpdateChampionship(ctx context.Context, arg UpdateChampionshipParams) (Championship, error)
}

var _ Querier = (*Queries)(nil)
