name: CI

on:
  push:
    branches-ignore:
      - "main"


jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.19.0"
      
      - name: run tests
        run: go test ./pkg/... -v -cover
