name: Deploy

on:
  push:
    tags:
      - "*.*.*"

env:
    DB_HOST: kandula.db.elephantsql.com
    DB_NAME: yzxtaxwb
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASS: ${{ secrets.DB_PASS }}

jobs:
    run_migration:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: "1.19.0"

        - name: run migration
          run: go run cmd/migrations/main.go dir up
          

    build_push:
      needs: [run_migration]
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push app image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: odotti/beerchampz:${{ github.ref_name }}
