name: Deploy

on:
  push:
    # tags:
    #   - "*.*.*"

env:
    DB_HOST: kandula.db.elephantsql.com
    DB_NAME: yzxtaxwb
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASS: ${{ secrets.DB_PASS }}
    SERVICE_NAME: beerchampz

# build and push the new image
# stop the execution on the server
# start the new image on the server

jobs:

    build_push:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push app image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: odotti/${{ env.SERVICE_NAME }}:${{ github.ref_name }}

    stop_server:
      needs: [build_push]
      runs-on: ubuntu-latest
      steps:
        - name: Stop execution on sever
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: "sudo docker stop ${{ env.SERVICE_NAME }}"

    run_migration:
      runs-on: ubuntu-latest
      needs: [build_push, stop_server]
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-go@v3
          with:
            go-version: "1.19.0"

        - name: run migration
          run: go run cmd/migrations/main.go -dir up

    start-server:
      runs-on: ubuntu-latest
      needs: [run_migration]
      steps:
        - name: Start execution on sever
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: "sudo docker run --name ${{ env.SERVICE_NAME }} -it -p --env-file .env 8080 odotti/${{ env.SERVICE_NAME }}:${{ github.ref_name }}"
